lam : 3.0 # 水路の波長(m)
nx0 : 31 # 格子数/1波長
ny : 15 # 横断方向格子数(奇数推奨)
wn : 2 # 波数
chb : 0.4 # 水路幅(m)
t0_degree : 40 # 最大蛇行偏角(Degree)
slope: 0.001 # 水路勾配
xsize: 20 # 計算結果をプロットする図の横スケール


amp : 0.015 # 初期河床砂州の波高(m)
delta : 0.2 # 初期河床砂州の位相差(m)

snu_0 : 1e-6 # 動粘性係数
hmin : 0.001 # 最小水深(m)
cw: 0.001 # 側壁摩擦係数
ep_alpha: 1. # 渦動粘性係数の係数

qp: 0.001 # 流量(m^3/s)
snm: 0.01 # マニング粗度
g: 9.8 # 重力加速度(m/s^2)

j_west: 0 # 上流条件(0:開放, 1:閉鎖)
j_east: 0 # 下流条件(0:開放, 1:閉鎖)
j_hdown: 1 # 下流端水位条件(0:自由流出, 1:等流水深, 2:固定水位を与える)
h_down : 1. # j_hdown=2 の時の固定水位(m)
j_inih: 2 #初期水位縦断 0:直線 1:等流計算　2:不等流計算

alh: 0.7 # 水位収束計算のReluxsation係数
lmax: 20 # 各タイムステップでの水位収束計算最大回数

etime: 100. # 計算終了時間(sec)
tuk: 1.0 # 計算結果アウトプット間隔(sec)
dt: 0.002 # 計算タイムステップ(sec)
stime: 0. # アウトプット開始時間(sec)

iskip: 1 # ベクトルプロットの i 方向間引き
jskip: 1 # ベクトルプロットの j 方向間引き
jscale: 10 # ベクトルのスケールファクター

vcolor : yellow # ベクトルのカラー